### ISSUE TITLE
Dying despite having resources

### ISSUE THREAD

**Issue by mayvillian** [walbrc27/cs341#13]
I don't know if this is hidden game logic, but I built a nuclear plant, a solar plant, and a food source. However, despite building these things, my power source was still drained after sitting around for about a minute.

**Comment by walbrc27** [comment]
I think this is just the difficulty of the game. We can scale it down (at least in normal mode) if needed - I will assign this to Grant and Cory.

**Comment by calewis1995** [comment]
Yeah, the longer you sit, the greater the amount of resources get drained per tick. I can scale it down by a factor of 10. This should, in theory, allow us to get over 1,000 watts before we really have to start fighting. Right now I can't even reach 200.

**Comment by walbrc27** [comment]
Sounds good Cory, I'll test out your changes now.
