### ISSUE TITLE
Fix Hunger scaling

### ISSUE THREAD

**Issue by walbrc27** [walbrc27/cs341#8]
Currently, your hunger doesn't seem to increase the longer you play the game - or at least if it does, it doesn't do so very quickly.

**Comment by calewis1995** [comment]
Once you build a food source they tend to cancel out. Similar to the Power source issue.

**Comment by walbrc27** [comment]
I meant the amount of hunger you gain per second doesn't increase. We should make that go up the same way Power costs do, with time. But whoever implements this change, make sure your hunger gain per Tick is never greater than like 50, because we can only have like 50 hunger max (this means you also have to add a check to make sure hunger gain (50) + current hunger < 100).
